# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CastingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='Мыло')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Мобилка')),
                ('email_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='')),
                ('phone_number_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=20, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('contacts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='castingapp.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('original', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('id_c', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Employer')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('growth', models.IntegerField(verbose_name='Рост в сантиметрах')),
                ('clothsize', models.IntegerField(verbose_name='Размер одежды (40, 43, 48..)')),
                ('chestsize', models.IntegerField(verbose_name='Обхват груди в сантиметрах')),
                ('waistsize', models.IntegerField(verbose_name='Обхват талии в сантиметрах')),
                ('thighsize', models.IntegerField(verbose_name='Обхват бедер в сантиемтрах')),
                ('footsize', models.IntegerField(verbose_name='Размер обуви')),
                ('necksize', models.IntegerField(blank=True, null=True, verbose_name='Обхват шеи в сантиметрах')),
                ('headsize', models.IntegerField(blank=True, null=True, verbose_name='Обхват головы в сантиметрах')),
                ('tatu', models.BooleanField(default=False, verbose_name='Наличие татуировок')),
                ('piercing', models.BooleanField(default=False, verbose_name='Наличие пирсинга')),
                ('appearancetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.AppearanceType')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Country')),
                ('employmenttype', models.ManyToManyField(blank=True, to='castingapp.EmploymentType')),
                ('eyecolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.EyeColor')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Gender')),
                ('haircolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.HairColor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('amount', models.FloatField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('casting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Casting')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Role'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.RequestStatus'),
        ),
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='param_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Parameters'),
        ),
        migrations.AddField(
            model_name='casting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.Employee'),
        ),
        migrations.AddField(
            model_name='casting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castingapp.CastingType'),
        ),
    ]
