# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0003_auto_20171115_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='human_rating',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='professional_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='employee',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='castingapp.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(1, '1'), (5, '5'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(1, '1'), (5, '5'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
