# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0004_auto_20171115_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(5, '5'), (3, '3'), (1, '1'), (2, '2'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(5, '5'), (3, '3'), (1, '1'), (2, '2'), (4, '4')]),
        ),
    ]
