# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0005_auto_20171115_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (2, '2'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (2, '2'), (4, '4')]),
        ),
    ]
