# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0006_auto_20171115_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(1, '1'), (4, '4'), (3, '3'), (5, '5'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(1, '1'), (4, '4'), (3, '3'), (5, '5'), (2, '2')]),
        ),
    ]
