# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('castingapp', '0008_auto_20171121_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_employee'),
        ),
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (4, '4'), (5, '5'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (4, '4'), (5, '5'), (2, '2')]),
        ),
    ]
