# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0009_auto_20171125_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='test_img')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (1, '1'), (2, '2'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (1, '1'), (2, '2'), (4, '4')]),
        ),
    ]
