# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0013_auto_20171126_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='param_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='castingapp.Parameters'),
        ),
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(5, '5'), (3, '3'), (1, '1'), (2, '2'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(5, '5'), (3, '3'), (1, '1'), (2, '2'), (4, '4')]),
        ),
    ]
