# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0015_auto_20171126_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Наниматель'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Наемник'},
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='human_skills',
            field=models.IntegerField(choices=[(5, '5'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professional_skills',
            field=models.IntegerField(choices=[(5, '5'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
